-- FlatMatch schema. Paste into Supabase → SQL Editor → Run. Safe to re-run.
--
-- Access model: there is no user auth. The Next.js server talks to Postgres with the
-- service_role key (which bypasses RLS). RLS is enabled with NO policies, so the public
-- anon key can't read anything: members' answers are only released by the server,
-- and only once all three have submitted.

create extension if not exists pgcrypto;

create table if not exists groups (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z0-9]{6}$'),
  status text not null default 'collecting' check (status in ('collecting', 'complete')),
  results jsonb,                -- snapshot of the latest match results
  results_updated_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists members (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references groups (id) on delete cascade,
  slot smallint not null check (slot between 1 and 3),
  name text not null check (char_length(name) between 1 and 30),
  submitted_at timestamptz,
  edit_token text,              -- held by the submitting browser; required to view/edit her answers
  unique (group_id, slot)
);

create table if not exists preferences (
  member_id uuid primary key references members (id) on delete cascade,
  data jsonb not null,          -- see lib/types.ts → Preferences
  updated_at timestamptz not null default now()
);

create table if not exists listings (
  id text primary key default gen_random_uuid()::text,
  group_id uuid references groups (id) on delete cascade,  -- null = shared seed listing
  title text not null,
  area text not null,
  bhk smallint not null check (bhk between 1 and 6),
  rent integer not null check (rent > 0),
  floor smallint not null check (floor >= 0),
  total_floors smallint not null check (total_floors >= 0),
  has_lift boolean not null default false,
  parking boolean not null default false,
  bathrooms smallint not null check (bathrooms between 1 and 6),
  pet_friendly boolean not null default false,
  furnished text not null check (furnished in ('unfurnished', 'semi', 'full')),
  amenities text[] not null default '{}',
  description text,
  source text not null default 'manual' check (source in ('seed', 'manual', 'pasted')),
  created_at timestamptz not null default now()
);

create index if not exists members_group_idx on members (group_id);
create index if not exists listings_group_idx on listings (group_id);

alter table groups enable row level security;
alter table members enable row level security;
alter table preferences enable row level security;
alter table listings enable row level security;

-- BEGIN SEED LISTINGS (generated by `npm run seed:sql` from lib/seed-listings.ts)
insert into listings (id, title, area, bhk, rent, floor, total_floors, has_lift, parking, bathrooms, pet_friendly, furnished, amenities, description, source) values
  ('seed-01', 'Sunny 3BHK near Balewadi High Street', 'Balewadi', 3, 42000, 6, 14, true, true, 3, true, 'semi', array['balcony', 'gym', 'power_backup', 'security']::text[], 'Gated society, covered parking, 5 min walk to High Street.', 'seed'),
  ('seed-02', 'Fully furnished 3BHK off Kunal Icon Road', 'Pimple Saudagar', 3, 39000, 3, 12, true, true, 2, true, 'full', array['gym', 'pool', 'power_backup', 'security']::text[], 'Modular kitchen, ACs in two rooms, society pool.', 'seed'),
  ('seed-03', 'Quiet 3BHK on Sus Road, hill view', 'Pashan', 3, 36000, 2, 7, true, true, 2, true, 'unfurnished', array['balcony', 'garden', 'security']::text[], 'Green surroundings, large balcony facing the hills.', 'seed'),
  ('seed-04', '3BHK near Datta Mandir Chowk', 'Wakad', 3, 38000, 5, 12, true, true, 2, true, 'semi', array['balcony', 'gym', 'pool', 'near_metro', 'power_backup']::text[], 'Walkable to Wakad metro station, society gym and pool.', 'seed'),
  ('seed-05', 'Premium 3BHK on Pancard Club Road', 'Baner', 3, 44000, 8, 15, true, true, 3, true, 'full', array['balcony', 'gym', 'pool', 'near_metro', 'power_backup', 'security']::text[], 'Fully furnished, clubhouse, near Baner metro.', 'seed'),
  ('seed-06', 'Budget 3BHK at Balewadi Phata (walk-up)', 'Balewadi', 3, 34000, 3, 4, false, true, 2, true, 'semi', array['balcony', 'near_metro']::text[], 'Older building, 3rd floor, no lift.', 'seed'),
  ('seed-07', 'Spacious 3BHK at Shivar Chowk', 'Pimple Saudagar', 3, 48000, 10, 18, true, true, 3, true, 'full', array['balcony', 'gym', 'pool', 'power_backup', 'security']::text[], 'Large carpet area, three attached bathrooms.', 'seed'),
  ('seed-08', '3BHK on ITI Road', 'Aundh', 3, 43000, 4, 8, true, true, 2, false, 'semi', array['balcony', 'security']::text[], 'Central Aundh, no pets per society rules.', 'seed'),
  ('seed-09', '3BHK on Karve Road', 'Kothrud', 3, 32000, 2, 5, false, true, 2, true, 'semi', array['balcony', 'near_metro']::text[], 'Near Vanaz metro, walk-up building.', 'seed'),
  ('seed-10', '3BHK in Hinjewadi Phase 1 township', 'Hinjewadi', 3, 33000, 7, 20, true, true, 2, true, 'semi', array['gym', 'pool', 'security', 'power_backup', 'near_metro']::text[], 'Township with shuttle to IT parks.', 'seed'),
  ('seed-11', 'Furnished 3BHK near Phoenix Mall', 'Viman Nagar', 3, 52000, 9, 12, true, true, 3, true, 'full', array['balcony', 'gym', 'pool', 'power_backup', 'security']::text[], null, 'seed'),
  ('seed-12', '3BHK near EON IT Park', 'Kharadi', 3, 45000, 12, 22, true, true, 3, false, 'semi', array['balcony', 'gym', 'pool', 'security']::text[], null, 'seed'),
  ('seed-13', 'Designer 2BHK in Lane 6', 'Koregaon Park', 2, 55000, 2, 4, true, true, 2, true, 'full', array['balcony', 'garden', 'security']::text[], null, 'seed'),
  ('seed-14', 'Old-world 2BHK near MG Road', 'Camp', 2, 30000, 1, 3, false, false, 1, true, 'semi', array['balcony']::text[], null, 'seed'),
  ('seed-15', '3BHK in Model Colony', 'Shivajinagar', 3, 55000, 2, 6, true, true, 3, false, 'semi', array['balcony', 'security', 'near_metro']::text[], null, 'seed'),
  ('seed-16', '3BHK with deck, Kalyani Nagar', 'Kalyani Nagar', 3, 58000, 6, 10, true, true, 3, true, 'full', array['balcony', 'gym', 'pool', 'near_metro', 'security']::text[], null, 'seed'),
  ('seed-17', '3BHK near Magarpatta City', 'Hadapsar', 3, 40000, 5, 14, true, true, 2, true, 'semi', array['gym', 'garden', 'security', 'power_backup']::text[], null, 'seed'),
  ('seed-18', '3BHK in Bavdhan, near Chandni Chowk', 'Bavdhan', 3, 35000, 4, 7, true, true, 2, true, 'semi', array['balcony', 'garden']::text[], null, 'seed'),
  ('seed-19', 'Compact 2BHK in Baner', 'Baner', 2, 30000, 5, 11, true, true, 2, true, 'semi', array['balcony', 'gym']::text[], null, 'seed'),
  ('seed-20', 'Affordable 2BHK in Wakad', 'Wakad', 2, 24000, 3, 10, true, true, 2, false, 'unfurnished', array['security']::text[], null, 'seed'),
  ('seed-21', 'Furnished 3BHK with pool, Balewadi', 'Balewadi', 3, 40000, 11, 16, true, true, 2, false, 'full', array['balcony', 'gym', 'pool', 'power_backup', 'security']::text[], 'Society does not allow pets.', 'seed'),
  ('seed-22', '2BHK near NCL, Pashan', 'Pashan', 2, 26000, 1, 4, false, true, 2, true, 'unfurnished', array['garden']::text[], null, 'seed'),
  ('seed-23', 'Ground-floor 3BHK bungalow portion, Aundh', 'Aundh', 3, 45000, 0, 2, false, true, 2, false, 'unfurnished', array['garden']::text[], null, 'seed'),
  ('seed-24', '2BHK near Kothrud Depot', 'Kothrud', 2, 25000, 4, 7, true, true, 2, true, 'semi', array['near_metro']::text[], null, 'seed'),
  ('seed-25', 'Walk-up 3BHK near Govind Garden', 'Pimple Saudagar', 3, 37000, 1, 4, false, false, 2, true, 'semi', array['balcony']::text[], 'First floor, street parking only.', 'seed'),
  ('seed-26', '3BHK in Hinjewadi Phase 2', 'Hinjewadi', 3, 30000, 9, 18, true, true, 2, true, 'unfurnished', array['gym', 'security', 'power_backup']::text[], null, 'seed')
on conflict (id) do update set
  title = excluded.title, area = excluded.area, bhk = excluded.bhk, rent = excluded.rent, floor = excluded.floor,
  total_floors = excluded.total_floors, has_lift = excluded.has_lift, parking = excluded.parking, bathrooms = excluded.bathrooms,
  pet_friendly = excluded.pet_friendly, furnished = excluded.furnished, amenities = excluded.amenities,
  description = excluded.description, source = excluded.source;
-- END SEED LISTINGS
