import type { Listing } from "./types";

type Seed = Omit<Listing, "source" | "groupId">;

/**
 * Mock Pune listings (stand-in for 99acres / MagicBricks, which have no open API).
 * This file is the source of truth: `npm run seed:sql` rewrites the seed block in supabase/schema.sql.
 */
const seeds: Seed[] = [
  { id: "seed-01", title: "Sunny 3BHK near Balewadi High Street", area: "Balewadi", bhk: 3, rent: 42000, floor: 6, totalFloors: 14, hasLift: true, parking: true, bathrooms: 3, petFriendly: true, furnished: "semi", amenities: ["balcony", "gym", "power_backup", "security"], description: "Gated society, covered parking, 5 min walk to High Street." },
  { id: "seed-02", title: "Fully furnished 3BHK off Kunal Icon Road", area: "Pimple Saudagar", bhk: 3, rent: 39000, floor: 3, totalFloors: 12, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "full", amenities: ["gym", "pool", "power_backup", "security"], description: "Modular kitchen, ACs in two rooms, society pool." },
  { id: "seed-03", title: "Quiet 3BHK on Sus Road, hill view", area: "Pashan", bhk: 3, rent: 36000, floor: 2, totalFloors: 7, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "unfurnished", amenities: ["balcony", "garden", "security"], description: "Green surroundings, large balcony facing the hills." },
  { id: "seed-04", title: "3BHK near Datta Mandir Chowk", area: "Wakad", bhk: 3, rent: 38000, floor: 5, totalFloors: 12, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "semi", amenities: ["balcony", "gym", "pool", "near_metro", "power_backup"], description: "Walkable to Wakad metro station, society gym and pool." },
  { id: "seed-05", title: "Premium 3BHK on Pancard Club Road", area: "Baner", bhk: 3, rent: 44000, floor: 8, totalFloors: 15, hasLift: true, parking: true, bathrooms: 3, petFriendly: true, furnished: "full", amenities: ["balcony", "gym", "pool", "near_metro", "power_backup", "security"], description: "Fully furnished, clubhouse, near Baner metro." },
  { id: "seed-06", title: "Budget 3BHK at Balewadi Phata (walk-up)", area: "Balewadi", bhk: 3, rent: 34000, floor: 3, totalFloors: 4, hasLift: false, parking: true, bathrooms: 2, petFriendly: true, furnished: "semi", amenities: ["balcony", "near_metro"], description: "Older building, 3rd floor, no lift." },
  { id: "seed-07", title: "Spacious 3BHK at Shivar Chowk", area: "Pimple Saudagar", bhk: 3, rent: 48000, floor: 10, totalFloors: 18, hasLift: true, parking: true, bathrooms: 3, petFriendly: true, furnished: "full", amenities: ["balcony", "gym", "pool", "power_backup", "security"], description: "Large carpet area, three attached bathrooms." },
  { id: "seed-08", title: "3BHK on ITI Road", area: "Aundh", bhk: 3, rent: 43000, floor: 4, totalFloors: 8, hasLift: true, parking: true, bathrooms: 2, petFriendly: false, furnished: "semi", amenities: ["balcony", "security"], description: "Central Aundh, no pets per society rules." },
  { id: "seed-09", title: "3BHK on Karve Road", area: "Kothrud", bhk: 3, rent: 32000, floor: 2, totalFloors: 5, hasLift: false, parking: true, bathrooms: 2, petFriendly: true, furnished: "semi", amenities: ["balcony", "near_metro"], description: "Near Vanaz metro, walk-up building." },
  { id: "seed-10", title: "3BHK in Hinjewadi Phase 1 township", area: "Hinjewadi", bhk: 3, rent: 33000, floor: 7, totalFloors: 20, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "semi", amenities: ["gym", "pool", "security", "power_backup", "near_metro"], description: "Township with shuttle to IT parks." },
  { id: "seed-11", title: "Furnished 3BHK near Phoenix Mall", area: "Viman Nagar", bhk: 3, rent: 52000, floor: 9, totalFloors: 12, hasLift: true, parking: true, bathrooms: 3, petFriendly: true, furnished: "full", amenities: ["balcony", "gym", "pool", "power_backup", "security"] },
  { id: "seed-12", title: "3BHK near EON IT Park", area: "Kharadi", bhk: 3, rent: 45000, floor: 12, totalFloors: 22, hasLift: true, parking: true, bathrooms: 3, petFriendly: false, furnished: "semi", amenities: ["balcony", "gym", "pool", "security"] },
  { id: "seed-13", title: "Designer 2BHK in Lane 6", area: "Koregaon Park", bhk: 2, rent: 55000, floor: 2, totalFloors: 4, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "full", amenities: ["balcony", "garden", "security"] },
  { id: "seed-14", title: "Old-world 2BHK near MG Road", area: "Camp", bhk: 2, rent: 30000, floor: 1, totalFloors: 3, hasLift: false, parking: false, bathrooms: 1, petFriendly: true, furnished: "semi", amenities: ["balcony"] },
  { id: "seed-15", title: "3BHK in Model Colony", area: "Shivajinagar", bhk: 3, rent: 55000, floor: 2, totalFloors: 6, hasLift: true, parking: true, bathrooms: 3, petFriendly: false, furnished: "semi", amenities: ["balcony", "security", "near_metro"] },
  { id: "seed-16", title: "3BHK with deck, Kalyani Nagar", area: "Kalyani Nagar", bhk: 3, rent: 58000, floor: 6, totalFloors: 10, hasLift: true, parking: true, bathrooms: 3, petFriendly: true, furnished: "full", amenities: ["balcony", "gym", "pool", "near_metro", "security"] },
  { id: "seed-17", title: "3BHK near Magarpatta City", area: "Hadapsar", bhk: 3, rent: 40000, floor: 5, totalFloors: 14, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "semi", amenities: ["gym", "garden", "security", "power_backup"] },
  { id: "seed-18", title: "3BHK in Bavdhan, near Chandni Chowk", area: "Bavdhan", bhk: 3, rent: 35000, floor: 4, totalFloors: 7, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "semi", amenities: ["balcony", "garden"] },
  { id: "seed-19", title: "Compact 2BHK in Baner", area: "Baner", bhk: 2, rent: 30000, floor: 5, totalFloors: 11, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "semi", amenities: ["balcony", "gym"] },
  { id: "seed-20", title: "Affordable 2BHK in Wakad", area: "Wakad", bhk: 2, rent: 24000, floor: 3, totalFloors: 10, hasLift: true, parking: true, bathrooms: 2, petFriendly: false, furnished: "unfurnished", amenities: ["security"] },
  { id: "seed-21", title: "Furnished 3BHK with pool, Balewadi", area: "Balewadi", bhk: 3, rent: 40000, floor: 11, totalFloors: 16, hasLift: true, parking: true, bathrooms: 2, petFriendly: false, furnished: "full", amenities: ["balcony", "gym", "pool", "power_backup", "security"], description: "Society does not allow pets." },
  { id: "seed-22", title: "2BHK near NCL, Pashan", area: "Pashan", bhk: 2, rent: 26000, floor: 1, totalFloors: 4, hasLift: false, parking: true, bathrooms: 2, petFriendly: true, furnished: "unfurnished", amenities: ["garden"] },
  { id: "seed-23", title: "Ground-floor 3BHK bungalow portion, Aundh", area: "Aundh", bhk: 3, rent: 45000, floor: 0, totalFloors: 2, hasLift: false, parking: true, bathrooms: 2, petFriendly: false, furnished: "unfurnished", amenities: ["garden"] },
  { id: "seed-24", title: "2BHK near Kothrud Depot", area: "Kothrud", bhk: 2, rent: 25000, floor: 4, totalFloors: 7, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "semi", amenities: ["near_metro"] },
  { id: "seed-25", title: "Walk-up 3BHK near Govind Garden", area: "Pimple Saudagar", bhk: 3, rent: 37000, floor: 1, totalFloors: 4, hasLift: false, parking: false, bathrooms: 2, petFriendly: true, furnished: "semi", amenities: ["balcony"], description: "First floor, street parking only." },
  { id: "seed-26", title: "3BHK in Hinjewadi Phase 2", area: "Hinjewadi", bhk: 3, rent: 30000, floor: 9, totalFloors: 18, hasLift: true, parking: true, bathrooms: 2, petFriendly: true, furnished: "unfurnished", amenities: ["gym", "security", "power_backup"] },
];

export const SEED_LISTINGS: Listing[] = seeds.map((s) => ({ ...s, source: "seed", groupId: null }));
