import { SEED_LISTINGS } from "./seed-listings";

export const SEED_BEGIN = "-- BEGIN SEED LISTINGS (generated by `npm run seed:sql` from lib/seed-listings.ts)";
export const SEED_END = "-- END SEED LISTINGS";

const q = (s: string | undefined | null) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);

/** The INSERT for the seed listings, idempotent so schema.sql can be re-run safely. */
export function seedListingsSql(): string {
  const rows = SEED_LISTINGS.map((l) =>
    [
      q(l.id),
      q(l.title),
      q(l.area),
      l.bhk,
      l.rent,
      l.floor,
      l.totalFloors,
      l.hasLift,
      l.parking,
      l.bathrooms,
      l.petFriendly,
      q(l.furnished),
      `array[${l.amenities.map(q).join(", ")}]::text[]`,
      q(l.description),
      q("seed"),
    ].join(", "),
  );
  return [
    "insert into listings (id, title, area, bhk, rent, floor, total_floors, has_lift, parking, bathrooms, pet_friendly, furnished, amenities, description, source) values",
    rows.map((r) => `  (${r})`).join(",\n"),
    "on conflict (id) do update set",
    "  title = excluded.title, area = excluded.area, bhk = excluded.bhk, rent = excluded.rent, floor = excluded.floor,",
    "  total_floors = excluded.total_floors, has_lift = excluded.has_lift, parking = excluded.parking, bathrooms = excluded.bathrooms,",
    "  pet_friendly = excluded.pet_friendly, furnished = excluded.furnished, amenities = excluded.amenities,",
    "  description = excluded.description, source = excluded.source;",
  ].join("\n");
}
